export const productArray = [
  {
    id: 1,
    name: "Pizza Margarita",
    price: 12000,
    category: "Pizzas",
    description: "Pizza con salsa de tomate, mozzarella y albahaca fresca.",
  },
  {
    id: 2,
    name: "Pizza Clásica",
    price: 10000,
    category: "Pizzas",
    description: "Pizza tradicional con jamón, queso y aceitunas.",
  },
  {
    id: 3,
    name: "Lomo Saltado",
    price: 15000,
    category: "Peruana",
    description: "Carne salteada con cebolla, tomate y papas fritas.",
  },
  {
    id: 4,
    name: "Ceviche Mixto",
    price: 18000,
    category: "Peruana",
    description: "Pescado y mariscos frescos marinados en limón con cebolla y cilantro.",
  },
  {
    id: 5,
    name: "Ensalada César",
    price: 8000,
    category: "Ensaladas",
    description: "Lechuga romana con pollo, crutones y aderezo César.",
  },
  {
    id: 6,
    name: "Tacos al Pastor",
    price: 12000,
    category: "Mexicana",
    description: "Tacos de cerdo marinado con piña, cebolla y cilantro.",
  },
  {
    id: 7,
    name: "Sushi Roll Philadelphia",
    price: 14000,
    category: "Japonesa",
    description: "Roll de sushi con salmón, queso crema y pepino.",
  },
  {
    id: 8,
    name: "Churrasco con Papas",
    price: 20000,
    category: "Carnes",
    description: "Filete de res a la plancha acompañado con papas fritas.",
  },
  {
    id: 9,
    name: "Lasagna de Carne",
    price: 16000,
    category: "Pastas",
    description: "Lasaña al horno con carne molida, salsa de tomate y queso.",
  },
  {
    id: 10,
    name: "Tiramisú",
    price: 7000,
    category: "Postres",
    description: "Postre italiano con capas de bizcocho, café y mascarpone.",
  },
  {
    id: 11,
    name: "Hamburguesa Clásica",
    price: 11000,
    category: "Sandwiches",
    description: "Hamburguesa con carne 100% vacuno, lechuga, tomate y queso.",
  },
  {
    id: 12,
    name: "Pad Thai",
    price: 13500,
    category: "Tailandesa",
    description: "Fideos salteados con camarones, huevo, maní y salsa tamarindo.",
  },
  {
    id: 13,
    name: "Arepas con Queso",
    price: 9000,
    category: "Venezolana",
    description: "Arepas de maíz rellenas con queso derretido.",
  },
  {
    id: 14,
    name: "Pollo al Curry",
    price: 15000,
    category: "India",
    description: "Pollo cocinado con especias, leche de coco y arroz basmati.",
  },
  {
    id: 15,
    name: "Crepes de Nutella",
    price: 8000,
    category: "Postres",
    description: "Crepes dulces rellenos de Nutella y frutas frescas.",
  },
  {
    id: 16,
    name: "Empanadas Argentinas",
    price: 7000,
    category: "Empanadas",
    description: "Empanadas rellenas de carne, cebolla y huevo duro.",
  },
  {
    id: 17,
    name: "Ramen de Cerdo",
    price: 16000,
    category: "Japonesa",
    description: "Sopa japonesa con fideos, cerdo, huevo y caldo de miso.",
  },
  {
    id: 18,
    name: "Chilaquiles",
    price: 9500,
    category: "Mexicana",
    description: "Tortillas fritas bañadas en salsa verde con queso y crema.",
  },
  {
    id: 19,
    name: "Spaghetti Carbonara",
    price: 13000,
    category: "Pastas",
    description: "Pasta con salsa de huevo, queso parmesano y tocino.",
  },
  {
    id: 20,
    name: "Brownie con Helado",
    price: 8500,
    category: "Postres",
    description: "Brownie de chocolate servido con bola de helado de vainilla.",
  },
];

export const categoriesArray = [
  { id: 1, name: "Pizzas" },
  { id: 2, name: "Peruana" },
  { id: 3, name: "Ensaladas" },
  { id: 4, name: "Mexicana" },
  { id: 5, name: "Japonesa" },
  { id: 6, name: "Carnes" },
  { id: 7, name: "Pastas" },
  { id: 8, name: "Postres" },
];
